version: "3.9"
services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes: [pg-data:/var/lib/postgresql/data]
    restart: unless-stopped

  bot:
    build: ./bot
    env_file: .env
    depends_on: [db]
    restart: unless-stopped
    volumes:
      - /home/crazy_boy/.ssh/id_ed25519:/run/secrets/vpn_ssh_key:ro

volumes:
  pg-data:
